global.classic_stage = 1;
global.adventure_stage = 0;
global.bonus_stage = 1;
global.bonuslost = 0;
global.go = 0;
global.stage_name = "P=12";
global.bonusIndex = 1;
global.stage_name_long = "BEAT BONUS\nEARN CONTINUE!";
global.music_playing = 0;
global.music_song = 50;
global.coincount = 0;
