global.classic_stage = 1;
global.adventure_stage = 0;
global.go = 0;
global.stage_name = "P=30";
global.stage_name_long = "PHASE 30";
global.ball_oob = 0;
global.intermission = 0;
global.bonus_stage = 0;
global.bonuslost = 0;
global.music_playing = 0;
global.music_song = 125;
global.coincount = 3;
