global.p_system = part_system_create_layer("Particles", 1);
global.particle_ball = part_type_create();
part_type_sprite(global.particle_ball, 32, 0, 0, 0);
part_type_alpha2(global.particle_ball, 0.5, 0);
part_type_speed(global.particle_ball, 0, 0, 0, 0);
part_type_direction(global.particle_ball, 0, 0, 0, 0);
part_type_blend(global.particle_ball, 0);
part_type_life(global.particle_ball, 15, 15);
global.particle_goldenball = part_type_create();
part_type_sprite(global.particle_goldenball, 618, 0, 0, 0);
part_type_alpha2(global.particle_goldenball, 1, 0);
part_type_speed(global.particle_goldenball, 0, 0, 0, 0);
part_type_direction(global.particle_goldenball, 0, 0, 0, 0);
part_type_blend(global.particle_goldenball, 0);
part_type_life(global.particle_goldenball, 15, 15);
global.particle_goldenball_shine = part_type_create();
part_type_sprite(global.particle_goldenball_shine, 6, 0, 0, 0);
part_type_alpha1(global.particle_goldenball_shine, 1);
part_type_speed(global.particle_goldenball_shine, 0, 0, 0, 0);
part_type_direction(global.particle_goldenball_shine, 0, 0, 0, 0);
part_type_blend(global.particle_goldenball_shine, 0);
part_type_life(global.particle_goldenball_shine, 15, 15);
global.particle_glassball = part_type_create();
part_type_sprite(global.particle_glassball, 342, 0, 0, 0);
part_type_alpha2(global.particle_glassball, 0.5, 0);
part_type_speed(global.particle_glassball, 0, 0, 0, 0);
part_type_direction(global.particle_glassball, 0, 0, 0, 0);
part_type_blend(global.particle_glassball, 0);
part_type_life(global.particle_glassball, 15, 15);
global.particle_glassshard = part_type_create();
part_type_sprite(global.particle_glassshard, 418, 0, 0, 0);
part_type_alpha1(global.particle_glassshard, 1);
part_type_orientation(global.particle_glassshard, 0, 359, 0, 20, 1);
part_type_speed(global.particle_glassshard, 0, 0, 0, 0);
part_type_gravity(global.particle_glassshard, 0.5, 270);
part_type_blend(global.particle_glassshard, 0);
part_type_life(global.particle_glassshard, 15, 15);
global.particle_anton = part_type_create();
part_type_sprite(global.particle_anton, 251, 0, 0, 0);
part_type_alpha2(global.particle_anton, 0.75, 0);
part_type_speed(global.particle_anton, 0, 0, 0, 0);
part_type_direction(global.particle_anton, 0, 0, 0, 0);
part_type_blend(global.particle_anton, 0);
part_type_life(global.particle_anton, 20, 20);
global.particle_annie = part_type_create();
part_type_sprite(global.particle_annie, 310, 0, 0, 0);
part_type_alpha2(global.particle_annie, 0.75, 0);
part_type_speed(global.particle_annie, 0, 0, 0, 0);
part_type_direction(global.particle_annie, 0, 0, 0, 0);
part_type_blend(global.particle_annie, 0);
part_type_life(global.particle_annie, 20, 20);
global.particle_danton = part_type_create();
part_type_sprite(global.particle_danton, 941, 0, 0, 0);
part_type_alpha2(global.particle_danton, 0.75, 0);
part_type_speed(global.particle_danton, 0, 0, 0, 0);
part_type_direction(global.particle_danton, 0, 0, 0, 0);
part_type_blend(global.particle_danton, 0);
part_type_life(global.particle_danton, 20, 20);
global.particle_nina = part_type_create();
part_type_sprite(global.particle_nina, 649, 0, 0, 0);
part_type_alpha2(global.particle_nina, 0.75, 0);
part_type_speed(global.particle_nina, 0, 0, 0, 0);
part_type_direction(global.particle_nina, 0, 0, 0, 0);
part_type_blend(global.particle_nina, 0);
part_type_life(global.particle_nina, 20, 20);
global.particle_brulo = part_type_create();
part_type_sprite(global.particle_brulo, 763, 0, 0, 0);
part_type_alpha2(global.particle_brulo, 0.75, 0);
part_type_speed(global.particle_brulo, 0, 0, 0, 0);
part_type_direction(global.particle_brulo, 0, 0, 0, 0);
part_type_blend(global.particle_brulo, 0);
part_type_life(global.particle_brulo, 20, 20);
global.particle_paul = part_type_create();
part_type_sprite(global.particle_paul, 327, 0, 0, 0);
part_type_alpha2(global.particle_paul, 0.75, 0);
part_type_speed(global.particle_paul, 0, 0, 0, 0);
part_type_direction(global.particle_paul, 0, 0, 0, 0);
part_type_blend(global.particle_paul, 0);
part_type_life(global.particle_paul, 20, 20);
global.particle_snick = part_type_create();
part_type_sprite(global.particle_snick, 363, 0, 0, 0);
part_type_alpha2(global.particle_snick, 0.75, 0);
part_type_speed(global.particle_snick, 0, 0, 0, 0);
part_type_direction(global.particle_snick, 0, 0, 0, 0);
part_type_blend(global.particle_snick, 0);
part_type_life(global.particle_snick, 20, 20);
global.particle_antari = part_type_create();
part_type_sprite(global.particle_antari, 476, 0, 0, 0);
part_type_alpha2(global.particle_antari, 0.75, 0);
part_type_speed(global.particle_antari, 0, 0, 0, 0);
part_type_direction(global.particle_antari, 0, 0, 0, 0);
part_type_blend(global.particle_antari, 0);
part_type_life(global.particle_antari, 20, 20);
global.particle_redguy = part_type_create();
part_type_sprite(global.particle_redguy, 939, 0, 0, 0);
part_type_alpha2(global.particle_redguy, 0.75, 0);
part_type_speed(global.particle_redguy, 0, 0, 0, 0);
part_type_direction(global.particle_redguy, 0, 0, 0, 0);
part_type_blend(global.particle_redguy, 0);
part_type_life(global.particle_redguy, 20, 20);
global.particle_classicanton = part_type_create();
part_type_sprite(global.particle_classicanton, 801, 0, 0, 0);
part_type_alpha2(global.particle_classicanton, 0.75, 0);
part_type_speed(global.particle_classicanton, 0, 0, 0, 0);
part_type_direction(global.particle_classicanton, 0, 0, 0, 0);
part_type_blend(global.particle_classicanton, 0);
part_type_life(global.particle_classicanton, 20, 20);
global.particle_classicannie = part_type_create();
part_type_sprite(global.particle_classicannie, 433, 0, 0, 0);
part_type_alpha2(global.particle_classicannie, 0.75, 0);
part_type_speed(global.particle_classicannie, 0, 0, 0, 0);
part_type_direction(global.particle_classicannie, 0, 0, 0, 0);
part_type_blend(global.particle_classicannie, 0);
part_type_life(global.particle_classicannie, 20, 20);
global.particle_antonsdog = part_type_create();
part_type_sprite(global.particle_antonsdog, 243, 0, 0, 0);
part_type_alpha2(global.particle_antonsdog, 0.75, 0);
part_type_speed(global.particle_antonsdog, 0, 0, 0, 0);
part_type_direction(global.particle_antonsdog, 0, 0, 0, 0);
part_type_blend(global.particle_antonsdog, 0);
part_type_life(global.particle_antonsdog, 20, 20);
global.particle_anniescat = part_type_create();
part_type_sprite(global.particle_anniescat, 922, 0, 0, 0);
part_type_alpha2(global.particle_anniescat, 0.75, 0);
part_type_speed(global.particle_anniescat, 0, 0, 0, 0);
part_type_direction(global.particle_anniescat, 0, 0, 0, 0);
part_type_blend(global.particle_anniescat, 0);
part_type_life(global.particle_anniescat, 20, 20);
global.particle_bebo = part_type_create();
part_type_sprite(global.particle_bebo, 323, 0, 0, 0);
part_type_alpha2(global.particle_bebo, 0.75, 0);
part_type_speed(global.particle_bebo, 0, 0, 0, 0);
part_type_direction(global.particle_bebo, 0, 0, 0, 0);
part_type_blend(global.particle_bebo, 0);
part_type_life(global.particle_bebo, 20, 20);
global.particle_minimitt = part_type_create();
part_type_sprite(global.particle_minimitt, 224, 0, 0, 0);
part_type_alpha2(global.particle_minimitt, 0.75, 0);
part_type_speed(global.particle_minimitt, 0, 0, 0, 0);
part_type_direction(global.particle_minimitt, 0, 0, 0, 0);
part_type_blend(global.particle_minimitt, 0);
part_type_life(global.particle_minimitt, 20, 20);
global.particle_microdemon = part_type_create();
part_type_sprite(global.particle_microdemon, 660, 0, 0, 0);
part_type_alpha2(global.particle_microdemon, 0.75, 0);
part_type_speed(global.particle_microdemon, 0, 0, 0, 0);
part_type_direction(global.particle_microdemon, 0, 0, 0, 0);
part_type_blend(global.particle_microdemon, 0);
part_type_life(global.particle_microdemon, 20, 20);
global.particle_oldmanton = part_type_create();
part_type_sprite(global.particle_oldmanton, 871, 0, 0, 0);
part_type_alpha2(global.particle_oldmanton, 0.75, 0);
part_type_speed(global.particle_oldmanton, 0, 0, 0, 0);
part_type_direction(global.particle_oldmanton, 0, 0, 0, 0);
part_type_blend(global.particle_oldmanton, 0);
part_type_life(global.particle_oldmanton, 20, 20);
global.particle_antOnBall = part_type_create();
part_type_sprite(global.particle_antOnBall, 959, 0, 0, 0);
part_type_alpha2(global.particle_antOnBall, 0.75, 0);
part_type_speed(global.particle_antOnBall, 0, 0, 0, 0);
part_type_direction(global.particle_antOnBall, 0, 0, 0, 0);
part_type_blend(global.particle_antOnBall, 0);
part_type_life(global.particle_antOnBall, 20, 20);
global.particle_don = part_type_create();
part_type_sprite(global.particle_don, 281, 0, 0, 0);
part_type_alpha2(global.particle_don, 0.75, 0);
part_type_speed(global.particle_don, 0, 0, 0, 0);
part_type_direction(global.particle_don, 0, 0, 0, 0);
part_type_blend(global.particle_don, 0);
part_type_life(global.particle_don, 20, 20);
global.particle_cooper = part_type_create();
part_type_sprite(global.particle_cooper, 100, 0, 0, 0);
part_type_alpha2(global.particle_cooper, 0.75, 0);
part_type_speed(global.particle_cooper, 0, 0, 0, 0);
part_type_direction(global.particle_cooper, 0, 0, 0, 0);
part_type_blend(global.particle_cooper, 0);
part_type_life(global.particle_cooper, 20, 20);
global.particle_clive = part_type_create();
part_type_sprite(global.particle_clive, 896, 0, 0, 0);
part_type_alpha2(global.particle_clive, 0.75, 0);
part_type_speed(global.particle_clive, 0, 0, 0, 0);
part_type_direction(global.particle_clive, 0, 0, 0, 0);
part_type_blend(global.particle_clive, 0);
part_type_life(global.particle_clive, 20, 20);
global.particle_peppino = part_type_create();
part_type_sprite(global.particle_peppino, 587, 0, 0, 0);
part_type_alpha2(global.particle_peppino, 0.75, 0);
part_type_speed(global.particle_peppino, 0, 0, 0, 0);
part_type_direction(global.particle_peppino, 0, 0, 0, 0);
part_type_blend(global.particle_peppino, 0);
part_type_life(global.particle_peppino, 20, 20);
global.particle_bullet = part_type_create();
part_type_sprite(global.particle_bullet, 424, 1, 1, 0);
part_type_speed(global.particle_bullet, 0, 0, 0, 0);
part_type_direction(global.particle_bullet, 0, 0, 0, 0);
part_type_blend(global.particle_bullet, 0);
part_type_life(global.particle_bullet, 10, 10);
global.particle_300 = part_type_create();
part_type_sprite(global.particle_300, 477, 0, 0, 0);
part_type_speed(global.particle_300, 0.5, 0.5, 0, 0);
part_type_direction(global.particle_300, 90, 90, 0, 0);
part_type_blend(global.particle_300, 0);
part_type_life(global.particle_300, 60, 60);
global.particle_500mini = part_type_create();
part_type_sprite(global.particle_500mini, 478, 0, 0, 0);
part_type_speed(global.particle_500mini, 0.5, 0.5, 0, 0);
part_type_direction(global.particle_500mini, 90, 90, 0, 0);
part_type_blend(global.particle_500mini, 0);
part_type_life(global.particle_500mini, 60, 60);
global.particle_250mini = part_type_create();
part_type_sprite(global.particle_250mini, 490, 0, 0, 0);
part_type_speed(global.particle_250mini, 0.5, 0.5, 0, 0);
part_type_direction(global.particle_250mini, 90, 90, 0, 0);
part_type_blend(global.particle_250mini, 0);
part_type_life(global.particle_250mini, 60, 60);
global.particle_800mini = part_type_create();
part_type_sprite(global.particle_800mini, 486, 0, 0, 0);
part_type_speed(global.particle_800mini, 0.5, 0.5, 0, 0);
part_type_direction(global.particle_800mini, 90, 90, 0, 0);
part_type_blend(global.particle_800mini, 0);
part_type_life(global.particle_800mini, 60, 60);
global.particle_1600 = part_type_create();
part_type_sprite(global.particle_1600, 487, 0, 0, 0);
part_type_speed(global.particle_1600, 0.5, 0.5, 0, 0);
part_type_direction(global.particle_1600, 90, 90, 0, 0);
part_type_blend(global.particle_1600, 0);
part_type_life(global.particle_1600, 60, 60);
global.particle_2400 = part_type_create();
part_type_sprite(global.particle_2400, 488, 0, 0, 0);
part_type_speed(global.particle_2400, 0.5, 0.5, 0, 0);
part_type_direction(global.particle_2400, 90, 90, 0, 0);
part_type_blend(global.particle_2400, 0);
part_type_life(global.particle_2400, 60, 60);
global.particle_3200 = part_type_create();
part_type_sprite(global.particle_3200, 489, 0, 0, 0);
part_type_speed(global.particle_3200, 0.5, 0.5, 0, 0);
part_type_direction(global.particle_3200, 90, 90, 0, 0);
part_type_blend(global.particle_3200, 0);
part_type_life(global.particle_3200, 60, 60);
global.particle_n10000 = part_type_create();
part_type_sprite(global.particle_n10000, 498, 0, 0, 0);
part_type_speed(global.particle_n10000, 0.5, 0.5, 0, 0);
part_type_direction(global.particle_n10000, 90, 90, 0, 0);
part_type_blend(global.particle_n10000, 0);
part_type_life(global.particle_n10000, 60, 60);
global.particle_confetti = part_type_create();
part_type_sprite(global.particle_confetti, 524, 1, 0, 0);
part_type_speed(global.particle_confetti, 0.5, 0.5, 0, 0);
part_type_direction(global.particle_confetti, 230, 300, 0, 15);
part_type_blend(global.particle_confetti, 0);
part_type_life(global.particle_confetti, 400, 400);
