global.classic_stage = 0;
global.adventure_stage = 1;
global.go = 1;
global.stage_name = "P=1";
global.stage_name_long = "PHASE 1";
global.ball_oob = 0;
global.intermission = 0;
global.bonus_stage = 0;
global.bonuslost = 0;
global.music_playing = 1;
global.music_song = 31;
global.coincount = 0;
